## Data Preprocessing

In [1]:
import pandas as pd

### DataFrame creation

In [2]:
df = pd.DataFrame({
    'Age':[25,23,26,28,24],
    'Salary':[45000,50000,67000,56000,90000],
    'Gender':['Male','Female','Female','Male','Female'],
    'City':['Delhi','Mumbai',"Chennai",'Mumbai','Hyderabad'],
    'Education':['UG','PG','PHD',"PG",'UG']
})

### Data understanding

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        5 non-null      int64
 1   Salary     5 non-null      int64
 2   Gender     5 non-null      object
 3   City       5 non-null      object
 4   Education  5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

### checking the data

In [4]:
df

   Age  Salary  Gender       City Education
0   25   45000    Male      Delhi        UG
1   23   50000  Female     Mumbai        PG
2   26   67000  Female    Chennai       PHD
3   28   56000    Male     Mumbai        PG
4   24   90000  Female  Hyderabad        UG

### importing the preprocessing library

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

## Numerical data pre processing

### Standardizing the numerical columns

In [7]:
x = df[['Age','Salary']]
scaler = StandardScaler()
scale_data = scaler.fit_transform(x)
scale_data

array([[-0.11624764, -1.03863663],
       [-1.27872403, -0.72579427],
       [ 0.46499055,  0.33786975],
       [ 1.62746694, -0.35038344],
       [-0.69748583,  1.7769446 ]])

### Normalizing the numerical values

In [8]:
scaler = MinMaxScaler()
scale_data = scaler.fit_transform(x)
scale_data

array([[0.4       , 0.        ],
       [0.        , 0.11111111],
       [0.6       , 0.48888889],
       [1.        , 0.24444444],
       [0.2       , 1.        ]])

## Categorical data transformation
### One HotEncoding

In [43]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder(sparse_output=False)
encoded=encoder.fit_transform(df[['Gender','City']])
encoded

array([[0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

### ordinal encoading

In [44]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['UG','PG','PHD']])
encoded=encoder.fit_transform(df[['Education']])
encoded

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.]])

### lable encoding

In [45]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
encoded=encoder.fit_transform(df['Gender'])
encoded

array([1, 0, 0, 1, 0])

In [46]:
df['Gender_lable1'] = encoder.fit_transform(df['Gender'])

In [47]:
df

   Age  Salary  Gender       City Education  Gender_lable1
0   25   45000    Male      Delhi        UG              1
1   23   50000  Female     Mumbai        PG              0
2   26   67000  Female    Chennai       PHD              0
3   28   56000    Male     Mumbai        PG              1
4   24   90000  Female  Hyderabad        UG              0

In [48]:
print(dict(zip(encoder.classes_,encoder.transform(encoder.classes_))))

{'Female': np.int64(0), 'Male': np.int64(1)}

In [53]:
dummy = pd.get_dummies(df['Gender'],drop_first = True,dtype = int)

In [54]:
dummy

   Male
0     1
1     0
2     0
3     1
4     0